(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#2d3743" "#ff4242" "#74af68" "#dbdb95" "#34cae2" "#008b8b" "#00ede1" "#e1e1e0"])
 '(archive-extract-hook (quote (timvisher/make-read-only)))
 '(auto-insert (quote not-modified))
 '(auto-insert-mode t)
 '(background-color "#ffffff")
 '(background-mode dark)
 '(backup-directory-alist (\` (("." \, (concat (getenv "HOME") "/.emacs-backups")))))
 '(c-mode-common-hook (quote (timvisher/turn-on-subword-mode)))
 '(cider-repl-use-pretty-printing t)
 '(column-number-mode t)
 '(comment-column 0)
 '(compilation-message-face (quote default))
 '(css-indent-offset 3)
 '(cua-delete-selection nil)
 '(cua-enable-cua-keys nil)
 '(cua-global-mark-cursor-color "#2aa198")
 '(cua-normal-cursor-color "#657b83")
 '(cua-overwrite-cursor-color "#b58900")
 '(cua-read-only-cursor-color "#859900")
 '(cua-remap-control-v nil)
 '(cua-remap-control-z nil)
 '(cua-toggle-set-mark nil)
 '(cursor-color "#ffff00")
 '(custom-enabled-themes nil)
 '(custom-file "~/.emacs.d/timvisher/custom.el")
 '(custom-safe-themes
   (quote
    ("f22a0f5b85aed98055e4e5013cc104829d163067c03f8165ab03ae010d6e3d40" "ff9e6deb9cfc908381c1267f407b8830bcad6028231a5f736246b9fc65e92b44" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" "a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "5debeb813b180bd1c3756306cd8c83ac60fda55f85fb27249a0f2d55817e3cab" "117284df029007a8012cae1f01c3156d54a0de4b9f2f381feab47809b8a1caef" default)))
 '(custom-theme-directory "~/.emacs.d/site-lisp/themes")
 '(deft-directory "")
 '(deft-extension "md")
 '(deft-text-mode (quote markdown-mode))
 '(delete-selection-mode t)
 '(dired-dwim-target t)
 '(dired-recursive-copies (quote always))
 '(dired-recursive-deletes (quote always))
 '(dired-use-ls-dired (quote unspecified))
 '(erc-autoaway-mode t)
 '(erc-autojoin-channels-alist
   (quote
    (("freenode.net" "#clojure" "#emacs" "#nethack4" "#NetHack" "#ubuntu"))))
 '(erc-autojoin-delay 30)
 '(erc-autojoin-mode t)
 '(erc-autojoin-timing (quote ident))
 '(erc-email-userid "tim.visher@gmail.com")
 '(erc-enable-logging (quote erc-log-all-but-server-buffers))
 '(erc-keywords (quote ("\"vimgolf\"" "\"async\"")))
 '(erc-log-channels-directory "~/Dropbox/log")
 '(erc-log-mode t)
 '(erc-log-write-after-insert t)
 '(erc-nick "timvisher" t)
 '(erc-nick-notify-cmd "notify")
 '(erc-nick-uniquifier "t")
 '(erc-notifications-mode t)
 '(erc-prompt-for-nickserv-password nil)
 '(erc-prompt-for-password nil)
 '(erc-save-queries-on-quit t)
 '(erc-services-mode t)
 '(erc-text-matched-hook (quote (erc-log-matches)))
 '(erc-user-full-name "Tim Visher")
 '(find-ls-option (quote ("-print0 | xargs -0 ls -ld" . "-ld")))
 '(foreground-color "#ffff00")
 '(gc-cons-threshold 52428800)
 '(git-commit-max-summary-line-length 80)
 '(global-hl-line-mode t)
 '(global-hl-line-sticky-flag t)
 '(global-whitespace-mode t)
 '(grep-find-ignored-directories
   (quote
    ("SCCS" "RCS" "CVS" "MCVS" ".svn" ".git" ".hg" ".bzr" "_MTN" "_darcs" "{arch}" "target")))
 '(helm-M-x-always-save-history t)
 '(helm-c-use-adaptative-sorting t)
 '(helm-mode t)
 '(hippie-expand-try-functions-list
   (quote
    (try-complete-file-name-partially try-complete-file-name try-expand-all-abbrevs try-expand-dabbrev try-expand-dabbrev-all-buffers try-expand-dabbrev-from-kill try-complete-lisp-symbol-partially try-complete-lisp-symbol)))
 '(history-length 1000)
 '(ido-everywhere t)
 '(ido-save-directory-list-file "~/.emacs-ido.last")
 '(ido-ubiquitous-command-exceptions (quote (unhighlight-regexp)))
 '(ido-ubiquitous-mode t)
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote left))
 '(indicate-empty-lines t)
 '(inferior-lisp-program "lein repl")
 '(inhibit-startup-screen nil)
 '(isearch-allow-scroll t)
 '(ispell-program-name "aspell")
 '(js-indent-level 2)
 '(magit-diff-use-overlays nil)
 '(magit-use-overlays nil)
 '(markdown-css-paths (quote ("css/bootstrap.css" "css/custom.css")))
 '(mouse-avoidance-mode (quote banish) nil (avoid))
 '(org-agenda-files (quote ("~/Dropbox/budget-review.org")))
 '(org-hide-leading-stars t)
 '(org-insert-heading-respect-content t)
 '(org-src-fontify-natively t)
 '(save-interprogram-paste-before-kill t)
 '(save-place-file (concat (getenv "HOME") "/.emacs.places"))
 '(savehist-mode t)
 '(sensitive-root "~/Dropbox/sensitive")
 '(sentence-end-double-space nil)
 '(sh-basic-offset 2)
 '(sh-indentation 2)
 '(shell-prompt-pattern
   "^[^#$%>
]*[#$%>🐀 🐁 🐂 🐃 🐄 🐅 🐆 🐇 🐈 🐉 🐊 🐋 🐌 🐍 🐎 🐏 🐐 🐑 🐒 🐓 🐔 🐕 🐖 🐗 🐘 🐙 🐚 🐛 🐜 🐝 🐞 🐟 🐠 🐡 🐢 🐣 🐤 🐥 🐦 🐧 🐨 🐩 🐪 🐫 🐬🐭 🐮 🐯 🐰 🐱 🐲 🐳 🐴 🐵 🐶 🐷 🐸 🐹 🐺 🐻 🐼 🐽 🐾 😸 😹 😺 😻 😼 😽 😾 😿 🙀 🙈 🙉 🙊] *")
 '(solarized-contrast (quote high))
 '(sql-ms-options (quote ("-w" "15000" "-n")))
 '(sql-ms-program "osql")
 '(standard-indent 2)
 '(tab-width 2)
 '(text-mode-hook (quote (whitespace-mode text-mode-hook-identify)))
 '(transient-mark-mode nil)
 '(user-mail-address "tim.visher@gmail.com")
 '(visual-line-fringe-indicators (quote (left-curly-arrow right-curly-arrow)))
 '(whitespace-style
   (quote
    (trailing space-before-tab face indentation space-after-tab)))
 '(winner-dont-bind-my-keys t)
 '(winner-mode t nil (winner)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cua-rectangle ((t (:inherit region))))
 '(hl-line ((t nil)))
 '(magit-item-highlight ((t (:inherit hl-line))))
 '(match ((t (:inherit idle-highlight))))
 '(region ((t (:background "#eeeeee")))))
